version: "3.9"
services:
  bottorrent:
    container_name: bottorrent
    image: 0netx/bottorrent
    labels:
        poc.bottorrent.description: "bottorrent container"
    volumes:
        - ./data/path:/download        
        - ./data/log.txt:/app/log.txt
    env_file:
        - .env
    restart: unless-stopped        